BEGIN;

/* DROP */

DROP TABLE IF EXISTS "user",
"group",
"role",
"permission",
"recipe",
"etape",
"ingredient",
"quantity",
"comment",
"user_has_group",
"user_has_role",
"role_has_permission",
"recipe_has_ingredient",
"group_has_recipe",
"ingredient_has_quantity";

/* TABLE */

CREATE TABLE "role"(
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL
);

CREATE TABLE "permission"(
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" text NOT NULL
);  

CREATE TABLE "user"(
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL UNIQUE,
  "password" text NOT NULL,
  "pseudo" text NULL UNIQUE,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

CREATE TABLE "group"(
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "description" text NOT NULL  
);

CREATE TABLE "comment"(
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" text NOT NULL,
  "user_id" integer NOT NULL REFERENCES "user"("id")  
);

CREATE TABLE "recipe"(
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "user_id" integer NOT NULL REFERENCES "user"("id")  
);

CREATE TABLE "etape"(
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" text NOT NULL,
  "recipe_id" integer NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE
);


CREATE TABLE "quantity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" integer NOT NULL  
);

CREATE TABLE "ingredient" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,  
  "quantity_id" integer NOT NULL REFERENCES "quantity"("id")  
);


/* TABLE ASSOCIATION */

CREATE TABLE "user_has_group" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "user"("id"),
  "group_id" integer NOT NULL REFERENCES "group"("id"),
  UNIQUE ("user_id", "group_id")
);

CREATE TABLE "group_has_recipe" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer NOT NULL REFERENCES "group"("id"),
  "recipe_id" integer NOT NULL REFERENCES "recipe"("id"),
  UNIQUE ("group_id", "recipe_id")
);

CREATE TABLE "user_has_role" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL REFERENCES "user"("id"),
  "role_id" integer NOT NULL REFERENCES "role"("id"),
  UNIQUE ("user_id", "role_id")
);

CREATE TABLE "role_has_permission" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" integer NOT NULL REFERENCES "role"("id"),
  "permission_id" integer NOT NULL REFERENCES "permission"("id"),
  UNIQUE ("role_id", "permission_id")
);

CREATE TABLE "recipe_has_ingredient" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipe_id" integer NOT NULL REFERENCES "recipe"("id") ON DELETE CASCADE,
  "ingredient_id" integer NOT NULL REFERENCES "ingredient"("id"),
  UNIQUE ("recipe_id", "ingredient_id")
);

/*CREATE TABLE "ingredient_has_quantity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ingredient_id" integer NOT NULL REFERENCES "ingredient"("id"),
  "quantity_id" integer NOT NULL REFERENCES "quantity"("id"),
  UNIQUE ("ingredient_id", "quantity_id")
);*/

COMMIT;
